// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/net/kevinztw/playground/proto/playground.proto

package net.kevinztw.playground.proto;

public interface PutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1;</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
