// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/net/kevinztw/playground/proto/playground.proto

package net.kevinztw.playground.proto;

public interface VersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Version)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp val = 1;</code>
   * @return Whether the val field is set.
   */
  boolean hasVal();
  /**
   * <code>.google.protobuf.Timestamp val = 1;</code>
   * @return The val.
   */
  com.google.protobuf.Timestamp getVal();
  /**
   * <code>.google.protobuf.Timestamp val = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getValOrBuilder();

  /**
   * <code>bytes key = 2;</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bool completed = 3;</code>
   * @return The completed.
   */
  boolean getCompleted();
}
