// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/net/kevinztw/playground/proto/playground.proto

package net.kevinztw.storage.proto;

public interface GetRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1;</code>
   *
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();
}
